import { PersonaConfig, PostDraft, CrisisState, ResearchItem, AnalyticsOverview, EvolutionSignal, DraftLifecycleEvent } from '@/core/types';

export const INITIAL_PERSONA: PersonaConfig = {
  id: 'persona_solo_1',
  userId: 'user_1',
  version: 1,
  handle: 'solobuilder',
  displayName: 'Alex Rivers | Solo Founder',
  bio: 'Building profitable micro-SaaS products in public. Writing about audience leverage, systems over goals, and solo engineering.',
  niche: 'Micro-SaaS & Solopreneurship',
  targetAudience: 'Early-stage bootstrapped founders, indie hackers, and solo software engineers',
  tone: {
    primary: 'authoritative',
    styleTags: ['concise', 'no-fluff', 'data-backed'],
    forbiddenPhrases: ['game-changer', 'unprecedented', 'delve into', 'unlock the potential'],
  },
  pillars: [
    {
      id: 'pillar_scale',
      name: 'Solo Distribution & Revenue',
      weight: 45,
      description: 'Tactical breakdowns on getting first 1,000 customers without paid ads or marketing teams.',
      sampleHooks: [
        'Most founders think you need a team to hit $20k MRR.',
        'The distribution playbook that brought 5,000 users in 30 days.',
      ],
    },
    {
      id: 'pillar_systems',
      name: 'Engineering Systems for One',
      weight: 35,
      description: 'How to automate deployment, customer support, and QA as a single developer.',
      sampleHooks: [
        'My exact tech stack for running 3 profitable apps solo.',
        'Why I chose boring tech over the latest JavaScript framework.',
      ],
    },
    {
      id: 'pillar_mindset',
      name: 'Contrarian Lessons & Mindset',
      weight: 20,
      description: 'Challenging venture-backed narratives with bootstrapped reality.',
      sampleHooks: [
        'Stop checking analytics 14 times a day.',
        'The uncomfortable truth about product-market fit.',
      ],
    },
  ],
  createdAt: '2026-08-01T00:00:00.000Z',
  updatedAt: '2026-08-01T00:00:00.000Z',
  evolutionNotes: 'Baseline v1 Persona configured for Solopreneur audience.',
};

export const INITIAL_CRISIS_STATE: CrisisState = {
  isFrozen: false,
};

export const INITIAL_DRAFTS: PostDraft[] = [
  {
    id: 'draft_seed_01',
    pillarId: 'pillar_scale',
    content: `Most solo founders obsess over building features when they should be obsessing over distribution velocity.\n\nCode without an audience is just a personal diary.\n\n3 tactics to build distribution before writing your first line of code:`,
    thread: [
      `1. Curate a specific problem library:\nSpend 2 weeks answering questions in niche communities. The recurring friction points become your landing page headlines.`,
      `2. Ship public case studies:\nBreak down competitors' product flaws respectfully with metrics. Position yourself as the subject-matter authority.`,
      `3. Build in public with receipts:\nShare real MRR graphs and churn reasons. Vulnerability converts lurkers into brand advocates.`,
    ],
    hashtags: ['buildinpublic', 'saas'],
    status: 'COMPLIANCE_REVIEW',
    estimatedHookScore: 94,
    complianceReport: {
      passed: true,
      score: 98,
      violations: [],
      checkedAt: new Date().toISOString(),
    },
    suggestedScheduleTime: 'Tomorrow, 8:45 AM (Peak Engagement)',
    createdAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
  },
  {
    id: 'draft_seed_02',
    pillarId: 'pillar_systems',
    content: `The solo founder tech stack that generates $18k/month with $45/month server costs:\n\n• Next.js + Tailwind (frontend)\n• Postgres on Cloud SQL (data)\n• BigQuery (analytics & telemetry)\n• Background workers for async jobs\n\nSimplicity is the only real leverage.`,
    hashtags: ['solofounder', 'indiehackers'],
    status: 'APPROVED',
    estimatedHookScore: 89,
    complianceReport: {
      passed: true,
      score: 95,
      violations: [],
      checkedAt: new Date().toISOString(),
    },
    suggestedScheduleTime: 'Today, 5:30 PM',
    createdAt: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
  },
];

export const INITIAL_RESEARCH_ITEMS = [
  {
    id: 'res_01',
    pillarId: 'pillar_scale',
    category: 'AUDIENCE_FRICTION' as const,
    topic: 'Customer Problem Libraries vs Void Coding',
    summary: 'Solo builders spend months building features nobody asked for instead of extracting recurring community complaints.',
    seedAngle: 'Why founders should build a customer problem library before touching their database schema.',
    audiencePainPoint: 'Zero product-market traction after 3 months of isolated coding.',
  },
  {
    id: 'res_02',
    pillarId: 'pillar_systems',
    category: 'CASE_STUDY' as const,
    topic: 'Minimal Serverless Stack Under $50/Month',
    summary: 'Extreme infrastructure leverage: running 3 profitable micro-SaaS apps with Cloud SQL, Next.js, and BigQuery telemetry.',
    seedAngle: 'My exact tech stack for running 3 profitable micro-apps solo with zero DevOps overhead.',
    audiencePainPoint: 'Cloud bill anxiety and unnecessary Kubernetes complexity for solo devs.',
  },
  {
    id: 'res_03',
    pillarId: 'pillar_mindset',
    category: 'CONTRARIAN_THESIS' as const,
    topic: 'Bookmark Intent vs Vanity Likes',
    summary: 'The algorithm and revenue reward bookmarks and profile visits far more than surface-level likes. Focus on reference value.',
    seedAngle: 'Stop checking analytics 14 times a day: focus on high-intent bookmarks and distribution leverage.',
    audiencePainPoint: 'Vanity metric addiction that does not convert into Stripe notifications.',
  },
];

export const INITIAL_ANALYTICS_OVERVIEW: AnalyticsOverview = {
  authorHandle: 'solobuilder',
  period: 'Last 30 Days',
  totalImpressions: 87400,
  totalBookmarks: 1422,
  overallIntentScore: 7.68,
  complianceRate: 100,
  hookArchetypeROI: [
    {
      archetype: 'INVERSION',
      totalPosts: 14,
      totalImpressions: 42500,
      totalBookmarks: 810,
      totalProfileClicks: 142,
      avgEstimatedScore: 93.4,
      intentScore: 8.92,
      bookmarksPerKImpressions: 19.1,
      superHookPercentage: 42.9,
      performanceTier: 'SUPER_HOOK',
    },
    {
      archetype: 'HARD_DATA',
      totalPosts: 10,
      totalImpressions: 28100,
      totalBookmarks: 420,
      totalProfileClicks: 98,
      avgEstimatedScore: 90.2,
      intentScore: 7.15,
      bookmarksPerKImpressions: 14.9,
      superHookPercentage: 30.0,
      performanceTier: 'SOLID_PERFORMER',
    },
    {
      archetype: 'DIRECT_QUESTION',
      totalPosts: 6,
      totalImpressions: 16800,
      totalBookmarks: 192,
      totalProfileClicks: 64,
      avgEstimatedScore: 86.5,
      intentScore: 5.48,
      bookmarksPerKImpressions: 11.4,
      superHookPercentage: 16.7,
      performanceTier: 'SOLID_PERFORMER',
    },
  ],
  pillarBalance: [
    {
      pillarId: 'pillar_scale',
      pillarName: 'Solo Distribution & Revenue',
      targetWeightPct: 45,
      publishedCount: 14,
      actualSharePct: 46.7,
      skewPct: 1.7,
      pillarIntentScore: 8.45,
      allocationStatus: 'ON_TARGET',
    },
    {
      pillarId: 'pillar_systems',
      pillarName: 'Lean Engineering & Stack',
      targetWeightPct: 35,
      publishedCount: 11,
      actualSharePct: 36.7,
      skewPct: 1.7,
      pillarIntentScore: 7.62,
      allocationStatus: 'ON_TARGET',
    },
    {
      pillarId: 'pillar_mindset',
      pillarName: 'Solopreneur Reality',
      targetWeightPct: 20,
      publishedCount: 5,
      actualSharePct: 16.7,
      skewPct: -3.3,
      pillarIntentScore: 6.12,
      allocationStatus: 'ON_TARGET',
    },
  ],
  creatorPreferences: {
    totalDrafts: 38,
    approvedDrafts: 30,
    dismissedDrafts: 4,
    hookSwappedDrafts: 9,
    hookSwapRatePct: 23.7,
    approvalRatePct: 78.9,
    preferredArchetype: 'INVERSION',
    avgTimeToApprovalSeconds: 145,
    creatorCurationStyle: 'SELECTIVE_EDITOR',
  },
  telemetryEngine: 'mock',
  updatedAt: new Date().toISOString(),
};

export const INITIAL_EVOLUTION_SIGNALS: EvolutionSignal[] = [
  {
    id: 'sig_01_hook_inversion',
    type: 'HIGH_PERFORMING_HOOK',
    confidence: 0.94,
    evidence: {
      tweetIds: ['tw_inv_14', 'tw_inv_18'],
      metricComparison: 'Bookmarks are 3.2x higher on posts using "Contrarian Inversion" hooks (8.92% intent score vs 5.48% baseline).',
    },
    proposedAdjustment: {
      field: 'tone',
      currentValue: ['concise', 'no-fluff', 'data-backed'],
      proposedValue: ['concise', 'no-fluff', 'data-backed', 'contrarian-inversion'],
      rationale: 'Double down on high-intent bookmark retention by establishing contrarian inversion as an active voice tag.',
    },
    draftingImpact: 'Stage 4 Grok Drafter will prioritize Contrarian Inversion hook angles across all content pillars.',
    status: 'PENDING_APPROVAL',
    createdAt: 'Today',
  },
  {
    id: 'sig_02_fatigue_keywords',
    type: 'AUDIENCE_FATIGUE',
    confidence: 0.89,
    evidence: {
      tweetIds: ['tw_hype_03', 'tw_hype_07'],
      metricComparison: 'Hype buzzwords like "skyrocket" or "insane" triggered 40% higher negative triage sentiment from audience.',
    },
    proposedAdjustment: {
      field: 'forbiddenPhrases',
      currentValue: ['game-changer', 'unprecedented'],
      proposedValue: ['game-changer', 'unprecedented', 'skyrocket', 'insane'],
      rationale: 'Expand brand-safety forbidden list to filter out engagement-bait terms and protect authentic creator trust.',
    },
    draftingImpact: 'Compliance Sentinel will automatically reject any draft containing "skyrocket" or "insane".',
    status: 'PENDING_APPROVAL',
    createdAt: 'Yesterday',
  },
];

export const INITIAL_LIFECYCLE_EVENTS: DraftLifecycleEvent[] = [
  {
    eventId: 'evt_init_1',
    draftId: 'd_seed_1',
    authorHandle: 'solobuilder',
    eventType: 'DRAFT_CREATED',
    pillarId: 'pillar_scale',
    initialHookArchetype: 'HARD_DATA',
    selectedHookArchetype: 'INVERSION',
    isHookSwapped: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(),
  },
  {
    eventId: 'evt_init_2',
    draftId: 'd_seed_1',
    authorHandle: 'solobuilder',
    eventType: 'HOOK_SWAPPED',
    pillarId: 'pillar_scale',
    initialHookArchetype: 'HARD_DATA',
    selectedHookArchetype: 'INVERSION',
    isHookSwapped: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3 + 120000).toISOString(),
  },
  {
    eventId: 'evt_init_3',
    draftId: 'd_seed_1',
    authorHandle: 'solobuilder',
    eventType: 'APPROVED',
    pillarId: 'pillar_scale',
    selectedHookArchetype: 'INVERSION',
    isHookSwapped: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3 + 300000).toISOString(),
  },
  {
    eventId: 'evt_init_4',
    draftId: 'd_seed_2',
    authorHandle: 'solobuilder',
    eventType: 'DRAFT_CREATED',
    pillarId: 'pillar_scale',
    initialHookArchetype: 'DIRECT_QUESTION',
    selectedHookArchetype: 'INVERSION',
    isHookSwapped: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
  },
  {
    eventId: 'evt_init_5',
    draftId: 'd_seed_2',
    authorHandle: 'solobuilder',
    eventType: 'APPROVED',
    pillarId: 'pillar_scale',
    selectedHookArchetype: 'INVERSION',
    isHookSwapped: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2 + 180000).toISOString(),
  },
  {
    eventId: 'evt_init_6',
    draftId: 'd_seed_3',
    authorHandle: 'solobuilder',
    eventType: 'DISMISSED',
    pillarId: 'pillar_scale',
    initialHookArchetype: 'HARD_DATA',
    selectedHookArchetype: 'HARD_DATA',
    isHookSwapped: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 1).toISOString(),
  },
  {
    eventId: 'evt_init_7',
    draftId: 'd_seed_4',
    authorHandle: 'solobuilder',
    eventType: 'DISMISSED',
    pillarId: 'pillar_scale',
    initialHookArchetype: 'DIRECT_QUESTION',
    selectedHookArchetype: 'DIRECT_QUESTION',
    isHookSwapped: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
  },
];



